# Disable the newline at the start of the prompt
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[](bold green)"

[conda]
symbol = " "
format = "[$symbol$environment](green) "

[cmd_duration]
min_time = 2000
format = "took [$duration]($style)"
style = "yellow"

[directory]
truncation_length = 4
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"

[jobs]
symbol = " "
threshold = 1

[git_branch]
symbol = " "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 5

[git_state]
cherry_pick = "🍒 PICKING"

[git_status]
ahead = "⇡"
behind = "⇣"
staged.style = "green"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[memory_usage]
symbol = " "

[docker_context]
symbol = " "

[nodejs]
symbol = " "

[hostname]
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[ruby]
symbol = " "

[rust]
symbol = " "

[time]
time_format = "%T"
format = "at [$time]($style) "

[username]
disabled = true
show_always = false
style_user = "green"
style_root = "bold red"
